### ISSUE TITLE
Do not build on CentOS 8.2.2004

### ISSUE THREAD

**Issue by ak-ferhat** [lwfinger/rtl8192cu#7]
Hi
I tried to compile the driver for CentOS 8.2. 
The release is
> cat /etc/redhat-release
   CentOS Linux release 8.2.2004 (Core)
and the kernel is
> uname -a
   Linux localhost.localdomain 4.18.0-80.el8.x86_64 #1 SMP Tue Jun 4 09:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

with 
> make 
I get the following error:
 /home/abdou/install/rtl8192cu-master/os_dep/os_intfs.c:1020:22: error: initialisation de « u16 (*)(struct net_device *, struct sk_buff *, struct net_device *, u16 (*)(struct net_device *, struct sk_buff *, struct net_device *)) » {alias « short unsigned int (*)(struct net_device *, struct sk_buff *, struct net_device *, short unsigned int (*)(struct net_device *, struct sk_buff *, struct net_device *)) »} depuis le type pointeur « u16 (*)(struct net_device *, struct sk_buff *, void *, u16 (*)(struct net_device *, struct sk_buff *, struct net_device *)) » {alias « short unsigned int (*)(struct net_device *, struct sk_buff *, void *, short unsigned int (*)(struct net_device *, struct sk_buff *, struct net_device *)) »} qui est incompatible [-Werror=incompatible-pointer-types]
  .ndo_select_queue = rtw_select_queue,
                      ^~~~~~~~~~~~~~~~
/home/abdou/install/rtl8192cu-master/os_dep/os_intfs.c:1020:22: note: (près de l'initialisation de « rtw_netdev_ops.ndo_select_queue »)

In the fileI changed os_dep/os_intfs.c, line 962
       #elif (LINUX_VERSION_CODE >= KERNEL_VERSION(4, 19, 0))
to
      #elif (LINUX_VERSION_CODE >= KERNEL_VERSION(4, 18, 0))
There is no error but the following warning
WARNING: "wireless_send_event" [/home/abdou/install/rtl8192cu-master/rtl8192cu.ko] undefined!
  CC      /home/abdou/install/rtl8192cu-master/rtl8192cu.mod.o
  LD [M]  /home/abdou/install/rtl8192cu-master/rtl8192cu.ko

I get no errors
> su -c "make install"
install -p -m 644 rtl8192cu.ko  /lib/modules/4.18.0-80.el8.x86_64/kernel/drivers/net/wireless/
/sbin/depmod -a 4.18.0-80.el8.x86_64

with modprobe I get the error
> modprobe rtl8192cu
modprobe: ERROR: could not insert 'rtl8192cu': Unknown symbol in module, or unknown parameter (see dmesg)

I get the following output with dmesg
> dmesg |grep 8192cu
[ 1123.991098] rtl8192cu: loading out-of-tree module taints kernel.
[ 1123.991451] rtl8192cu: module verification failed: signature and/or required key missing - tainting kernel
[ 1123.991590] rtl8192cu: Unknown symbol wireless_send_event (err 0)

Please can you help me

**Comment by lwfinger** [comment]
You have the missing "wireless-send-event" because your kernel is built without wireless extensions. This driver needs CONFIG_WIRELESS_EXT=y.

**Comment by ak-ferhat** [comment]
> You have the missing "wireless-send-event" because your kernel is built without wireless extensions. This driver needs CONFIG_WIRELESS_EXT=y.

Thank you for the response.
If I understand I have to rebuild the kernel then build the driver.

**Comment by lwfinger** [comment]
Yes.

**Comment by ak-ferhat** [comment]
Thanks
